name: bio-core-tf
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - bioimageio.spec
  - conda-build
  - mypy
  - pip
  - pytest
  - python
  - xarray
  - tensorflow >=2.0,<3.0
  - tifffile <=2022.4.8  # pin fixes Syntax error; see https://github.com/bioimage-io/core-bioimage-io-python/pull/259
