name: Test and Deploy bioimageio.core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."
      - name: Annotate diff changes using reviewdog
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: blackfmt

  test-base-bioimage-spec-conda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channel-priority: strict
        activate-environment: bio-core-torch
        environment-file: dev/environment-torch.yaml
        python-version: ${{ matrix.python-version }}
    - name: additional setup
      shell: bash -l {0}
      run: pip install --no-deps -e .
    - name: pytest-base-bioimage-spec-conda
      shell: bash -l {0}
      run: pytest --disable-pytest-warnings

  test-base-bioimage-spec-main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        channel-priority: strict
        activate-environment: bio-core-torch
        environment-file: dev/environment-torch.yaml
        python-version: ${{ matrix.python-version }}
    - name: additional setup
      shell: bash -l {0}
      run: |
        conda remove --force bioimageio.spec
        pip install --no-deps git+https://github.com/bioimage-io/spec-bioimage-io
        pip install --no-deps -e .
    - name: pytest-base-bioimage-spec-main
      shell: bash -l {0}
      run: pytest --disable-pytest-warnings
  
  test-base-bioimage-spec-tf:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        # we need mamba to resolve environment-tf
        mamba-version: "*"
        channel-priority: flexible
        activate-environment: bio-core-tf
        environment-file: dev/environment-tf.yaml
        python-version: ${{ matrix.python-version }}
    - name: additional setup
      shell: bash -l {0}
      run: |
        conda remove --force bioimageio.spec
        pip install --no-deps git+https://github.com/bioimage-io/spec-bioimage-io
        pip install --no-deps -e .
    - name: pytest-base-bioimage-spec-tf
      shell: bash -l {0}
      run: pytest --disable-pytest-warnings

  test-base-bioimage-spec-tf-legacy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        # we need mamba to resolve environment-tf
        mamba-version: "*"
        channel-priority: flexible
        activate-environment: bio-core-tf-legacy
        environment-file: dev/environment-tf-legacy.yaml
        python-version: ${{ matrix.python-version }}
    - name: additional setup
      shell: bash -l {0}
      run: |
        conda remove --force bioimageio.spec
        pip install --no-deps git+https://github.com/bioimage-io/spec-bioimage-io
        pip install --no-deps -e .
    - name: pytest-base-bioimage-spec-tf-legacy
      shell: bash -l {0}
      run: pytest --disable-pytest-warnings

  conda-build:
    runs-on: ubuntu-latest
    needs: test-base-bioimage-spec-conda
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        auto-activate-base: true
        activate-environment: ""
    - name: linux conda build
      shell: bash -l {0}
      run: |
        conda install -n base -c conda-forge conda-build pip -y
        conda build -c conda-forge conda-recipe

  generate_workflow_rdfs:  # todo: move to contrib repo
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      # todo: use mamba envs
      run: |
        pip install . dask
    - name: Generate workflow RDFs
      run: python scripts/generate_workflow_rdfs.py  contrib_a
