name: Test and Deploy bioimageio.core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."
      - name: Annotate diff changes using reviewdog
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: blackfmt

  test-spec-conda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Install Conda environment with Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        cache-downloads: true
        cache-env: false  # debugging: torch does not detect onnxruntime
        environment-file: dev/environment-torch.yaml
        extra-specs: |
          python=${{ matrix.python-version }}
    - name: additional setup
      shell: bash -l {0}
      run: pip install --no-deps -e .
    - name: pytest-spec-conda
      shell: bash -l {0}
      run: pytest --disable-pytest-warnings

  test-spec-main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Install Conda environment with Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        cache-downloads: true
        cache-env: false  # todo: detect env cache hit and adapt(skip?) additional setup (conda remove?)
        environment-file: dev/environment-torch.yaml
        extra-specs: |
          python=${{ matrix.python-version }}
    - name: additional setup
      shell: bash -l {0}
      run: |
        conda remove --yes --force bioimageio.spec
        pip install --no-deps git+https://github.com/bioimage-io/spec-bioimage-io
        pip install --no-deps -e .
    - name: pytest-spec-main
      shell: bash -l {0}
      run: pytest --disable-pytest-warnings

  test-spec-tf:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Install Conda environment with Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        cache-downloads: true
        cache-env: false  # todo: detect env cache hit and adapt(skip?) additional setup (conda remove?)
        environment-file: dev/environment-tf.yaml
        channel-priority: flexible
        extra-specs: |
          python=${{ matrix.python-version }}
    - name: additional setup
      shell: bash -l {0}
      run: |
        conda remove --yes --force bioimageio.spec
        pip install --no-deps git+https://github.com/bioimage-io/spec-bioimage-io
        pip install --no-deps -e .
    - name: pytest-spec-tf
      shell: bash -l {0}
      run: pytest --disable-pytest-warnings

  test-spec-tf-legacy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Install Conda environment with Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        cache-downloads: false  # false for debugging: TypeError: Cannot handle this data type: (1, 1, 3), <f8
        cache-env: false  # false for debugging: TypeError: Cannot handle this data type: (1, 1, 3), <f8
        environment-file: dev/environment-tf-legacy.yaml
        channel-priority: flexible
        extra-specs: |
          python=${{ matrix.python-version }}
    - name: additional setup
      shell: bash -l {0}
      run: |
        conda remove --yes --force bioimageio.spec
        pip install --no-deps git+https://github.com/bioimage-io/spec-bioimage-io
        pip install --no-deps -e .
    - name: pytest-spec-tf-legacy
      shell: bash -l {0}
      run: pytest --disable-pytest-warnings

  conda-build:
    runs-on: ubuntu-latest
    needs: test-spec-conda
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Conda environment with Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        cache-downloads: true
        cache-env: true
        environment-file: false
        environment-name: build-env
        channels: conda-forge
        extra-specs: |
          boa
    - name: linux conda build
      shell: bash -l {0}
      run: |
        conda mambabuild -c conda-forge conda-recipe
