name: Test and Deploy bioimageio.core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

defaults:
  run:
    shell: bash -l {0}

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
          jupyter: true
          version: "23.7"

  test-spec-conda:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v3
    - name: Install Conda environment with Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        cache-downloads: true
        cache-environment: true
        environment-file: dev/environment-torch.yaml
        create-args: >-
          python=${{ matrix.python-version }}
    - name: additional setup
      run: pip install --no-deps -e .
    - name: pytest-spec-conda
      run: pytest --disable-pytest-warnings

  test-spec-main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v3
    - name: Install Conda environment with Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        cache-downloads: true
        cache-environment: true
        environment-file: dev/environment-torch.yaml
        create-args: >-
          python=${{ matrix.python-version }}
    - name: additional setup
      run: |
        conda remove --yes --force bioimageio.spec || true  # allow failure for cached env
        pip install --no-deps git+https://github.com/bioimage-io/spec-bioimage-io
        pip install --no-deps -e .
    - name: pytest-spec-main
      run: pytest --disable-pytest-warnings

  test-spec-tf:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v3
    - name: Install Conda environment with Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        cache-downloads: true
        cache-environment: true
        environment-file: dev/environment-tf.yaml
        condarc: |
          channel-priority: flexible
        create-args: >-
          python=${{ matrix.python-version }}
    - name: additional setup
      run: |
        conda remove --yes --force bioimageio.spec || true  # allow failure for cached env
        pip install --no-deps git+https://github.com/bioimage-io/spec-bioimage-io
        pip install --no-deps -e .
    - name: pytest-spec-tf
      run: pytest --disable-pytest-warnings

  test-spec-tf-legacy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v3
    - name: Install Conda environment with Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        cache-downloads: true
        cache-environment: true
        environment-file: dev/environment-tf-legacy.yaml
        condarc: |
          channel_priority: flexible
        create-args: |
          python=${{ matrix.python-version }}
    - name: additional setup
      run: |
        conda remove --yes --force bioimageio.spec || true  # allow failure for cached env
        pip install --no-deps git+https://github.com/bioimage-io/spec-bioimage-io
        pip install --no-deps -e .
    - name: pytest-spec-tf-legacy
      run: pytest --disable-pytest-warnings

  conda-build:
    runs-on: ubuntu-latest
    needs: test-spec-conda
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Conda environment with Micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        cache-downloads: true
        cache-environment: true
        environment-name: build-env
        condarc: |
          channels:
          - conda-forge
        create-args: |
          boa
    - name: linux conda build
      run: |
        conda mambabuild -c conda-forge conda-recipe
